import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const root = resolve(import.meta.dirname, '..')
const sourcePath = resolve(root, 'src/cosmetics.ts')
const avatarPath = resolve(root, 'src/data/avatar.catalog.json')
const jsonTarget = resolve(root, 'supabase/functions/account-api/cosmetic-catalog.json')
const sqlTarget = resolve(root, 'output/supabase-cosmetic-catalog.sql')

function exportedArray(source, name) {
  const marker = `export const ${name}`
  const declaration = source.indexOf(marker)
  const assignment = source.indexOf('=', declaration)
  const start = source.indexOf('[', assignment)
  if (declaration < 0 || start < 0) throw new Error(`${name} est introuvable.`)
  let depth = 0
  let quote = ''
  let escaped = false
  for (let index = start; index < source.length; index += 1) {
    const character = source[index]
    if (quote) {
      if (escaped) escaped = false
      else if (character === '\\') escaped = true
      else if (character === quote) quote = ''
      continue
    }
    if (character === "'" || character === '"' || character === '`') { quote = character; continue }
    if (character === '[') depth += 1
    if (character === ']' && --depth === 0) {
      // Source-controlled literal arrays: evaluating only the extracted array keeps
      // the database catalog generated from the same definitions as the UI.
      return Function('NO_ANIMATION_ID', `"use strict"; return (${source.slice(start, index + 1)})`)('animation-none')
    }
  }
  throw new Error(`${name} est incomplet.`)
}

const sourceText = await readFile(sourcePath, 'utf8')
const avatarFile = JSON.parse(await readFile(avatarPath, 'utf8'))
const avatarPrices = { human: 1_400, animal: 1_800, object: 2_200, flag: 1_400 }
const avatarRarity = avatar => avatar.kind === 'human' || avatar.kind === 'flag' ? 'commun' : avatar.kind === 'animal' ? 'singulier' : 'rare'
const items = [
  ...avatarFile.avatars.map(avatar => ({
    kind: 'avatar', id: avatar.id, name: avatar.name, rarity: avatar.availability === 'starter' ? 'commun' : avatarRarity(avatar),
    pricePlumes: avatar.availability === 'starter' ? 0 : avatarPrices[avatar.kind], availability: avatar.availability,
    asset: avatar.asset ?? null, active: avatar.availability !== 'retire',
  })),
  ...exportedArray(sourceText, 'FRAMES').map(item => ({ kind: 'frame', id: item.id, name: item.name, rarity: item.rarity, pricePlumes: item.pricePlumes, availability: item.availability, asset: item.asset ?? null })),
  ...exportedArray(sourceText, 'ANIMATIONS').map(item => ({ kind: 'animation', id: item.id, name: item.name, rarity: item.rarity, pricePlumes: item.pricePlumes, availability: item.availability, asset: item.asset ?? null })),
]
const baskets = exportedArray(sourceText, 'BASKETS').map(item => ({ id: item.id, name: item.name, pricePlumes: item.pricePlumes }))
const catalog = { version: 1, items, baskets }
await writeFile(jsonTarget, `${JSON.stringify(catalog, null, 2)}\n`, 'utf8')

const literal = value => `'${String(value).replaceAll("'", "''")}'`
const rows = items.map(item => `(${literal(item.kind)},${literal(item.id)},${literal(item.name)},${literal(item.rarity)},${item.pricePlumes},${literal(item.availability)},${item.asset ? literal(item.asset) : 'null'},${item.active === false ? 'false' : 'true'})`).join(',\n')
const basketRows = baskets.map(item => `(${literal(item.id)},${literal(item.name)},${item.pricePlumes},true)`).join(',\n')
await writeFile(sqlTarget, `-- Generated by scripts/build_supabase_cosmetic_catalog.mjs\ninsert into public.server_cosmetic_catalog (kind,item_id,name,rarity,price_feathers,availability,asset,active) values\n${rows}\non conflict (kind,item_id) do update set name=excluded.name,rarity=excluded.rarity,price_feathers=excluded.price_feathers,availability=excluded.availability,asset=excluded.asset,active=excluded.active;\n\ninsert into public.server_basket_catalog (id,name,price_feathers,active) values\n${basketRows}\non conflict (id) do update set name=excluded.name,price_feathers=excluded.price_feathers,active=excluded.active;\n`, 'utf8')
console.log(JSON.stringify({ items: items.length, baskets: baskets.length, jsonTarget, sqlTarget }))
